apiVersion: v1
kind: Service
metadata:
  name: my-restapi
  labels:
    backend: my-restapi
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 4000
    protocol: TCP
  selector:
    backend: my-restapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-restapi
spec:
  selector:
    matchLabels:
      backend: my-restapi
  replicas: 1
  template:
    metadata:
      labels:
        backend: my-restapi
    spec:
      containers:
      - name: testapi
        image: ispang13/test-api:85
        ports:
        - containerPort: 4000