apiVersion: v1
kind: Pod
metadata:
  name: restapi-mysql
  labels:
    app:  restapi-mysql
spec:

  containers:
  - name: test-api
    image: ispang13/test-api:65
       
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-mysql
spec:
  selector:
    app: restapi-mysql
  ports:
  - name: api-service-port
    protocol: TCP
    port: 4000
    targetPort: 4000
  