apiVersion: v1
kind: Pod
metadata:
  name: restapi-mysql
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: test-api
    image: ispang13/test-api:70
    ports:
      - containerPort: 4000
       
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-mysql
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: api-service-port
    protocol: TCP
    port: 80
    targetPort: 4000
  