apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi-mysql
  template:
    metadata:
      labels:
        app: restapi-mysql
    spec:
      containers:
      - name: test-api
        image: ispang13/test-api:48