apiVersion: v1
kind: Pod
metadata:
  name: restapi-mysql
  labels:
    app:  restapi-mysql
spec:

  containers:
  - name: test-api
    image: ispang13/test-api:68
    ports:
      - containerPort: 4000
        name: http-web-svc
       
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-mysql
spec:
  selector:
    app: restapi-mysql
  ports:
  - name: api-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  