apiVersion: v1
kind: Service
metadata:
  name: restapi-mysql
  labels:
    run: restapi-mysql
  namespace: react-app
spec:
  selector:
    app: restapi-mysql
  ports:
    - protocol: TCP
      port: 4000