apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react
  template:
    metadata:
      labels:
        app: my-react
    spec:
      containers:
      - name: my-react
        image: ispang13/react-app:58
