apiVersion: v1    #version of API in use
kind: Service     #resource to define
metadata:         #metadata of the resource
  name: my-react-svc
  labels:
    app: react
spec:             # Describe the desired state of the resource                 
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: react
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react
  labels:
    app: react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: react-app
        ports:
        - containerPort: 80