apiVersion: v1
kind: Service
metadata:
  name: my-react
  labels:
    run: my-react
spec:
  type: NodePort
  selector:
    app: my-react
  ports:
    - protocol: TCP
      port: 3000 
      targetPort: 3000
      nodePort: 3000

